{
 "title": "fitbit",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "bucket name", "query": "bucket0" }
  ]
 },
 "panels": [
  {
   "title": "Device Battery Level",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DeviceBatteryLevel\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> yield(name: \"value\")\r\n"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeartRate_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> movingAverage(n: 6)\r\n  |> yield(name: \"value\")\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeartRate_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r._value > 120)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> movingAverage(n: 6)\r\n  |> yield(name: \"high\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HeartRate_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r._value <= 60)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> movingAverage(n: 6)\r\n  |> yield(name: \"low\")"
    }
   ]
  },
  {
   "title": "RHR",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket0\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RestingHR\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> yield(name: \"value\")"
    }
   ]
  },
  {
   "title": "Hourly Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"bucket0\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Steps_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> movingAverage(n: 6)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket0\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Spo2 Today",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"bucket0\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SPO2_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Daily walk",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"bucket0\")\r\n  |> range(start: -7d, stop: 0d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Steps_Intraday\")\r\n  |> filter(fn: (r) => r[\"Device\"] == \"'Sense2'\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")\r\n  "
    }
   ]
  }
 ]
}